language: python

notifications:
  email: false

matrix:
  include:
  
    - os: linux
      sudo: required
      services: docker
      python: '3.6'
  
    - os: linux
      dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required
      services: docker
      python: '3.7'


# The Travis CI job lifecycle: https://docs.travis-ci.com/user/job-lifecycle/

# -------------------- install: install any dependencies required -------------
before_install:
  - sudo apt install libpython3.6-dev libpython3.7-dev;
  - uname --all # Print system information
  - python --version

install:
  - pip install black
  - pip install pytest


# -------------------- script: run the build script ---------------------------
before_script:
  - echo 'before script.'

script:
  - python setup.py develop sdist # Install the package
  - black . --check
  - pytest . --verbose --doctest-modules


# =============================================================================
# before_install
# install
# before_script
# script
# OPTIONAL before_cache (for cleaning up cache)
# after_success or after_failure
# OPTIONAL before_deploy
# OPTIONAL deploy
# OPTIONAL after_deploy
# after_script
# =============================================================================
