language: python

notifications:
  email: false

matrix:
  include:
  
    - os: linux
      sudo: required
      services: docker
      python: '3.6'
  
    - os: linux
      dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required
      services: docker
      python: '3.7'


# The Travis CI job lifecycle specifies the order of the commands below phases.
# https://docs.travis-ci.com/user/job-lifecycle/#the-job-lifecycle

# -------------------- install: install any dependencies required -------------
before_install:
  - sudo apt install libpython-dev
  - uname --all # Print system information
  - python --version

install:
  - pip install -r requirements.txt
  - pip list # List installed packages.


# -------------------- script: run the build script ---------------------------
before_script:
  - echo 'before script.'

script:
  - python setup.py develop sdist # Install the package
  - pip show statscollection
  - black . --check
  - flake8 statscollection --select=F401 # unused imports
  - pytest . --verbose --doctest-modules
  - sphinx-build doc/ html/


# =============================================================================
# before_install
# install
# before_script
# script
# OPTIONAL before_cache (for cleaning up cache)
# after_success or after_failure
# OPTIONAL before_deploy
# OPTIONAL deploy
# OPTIONAL after_deploy
# after_script
# =============================================================================
